---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: community-service-credential
  namespace: linkfolio
spec:
  encryptedData:
    MYSQL_PASSWORD: AgCoe7KF+E5OyBlwZOQdmRgoszvjChdmSPAoiv10ypB/5kSmvIlrzyubo6hl7tKyxt0jtS9hljDTAr7uXuRyPMV6DUne4rACv0WcmtMZXlQriOBdlV0TncWW4BtRlBIL6+FktBz1oR2sxUMOJQNywuw2qEhOM5ZmgIH7ym3dlKm2gYgr0C5zcSEJD22XE7hzCIZambVI8b3gjttXKog+nLBTdhXxWgEdfSP97lJ1JfEOqaygKkun7HKsIVpiMj5XI/6fkFxiFbQ4JcHWGOut5tMIYsJGTzmqJRASbVBSlzUzz5CDZhn999FK4AQ3IQDblKaYX1Pz/3jMuG2BMlx5goVeBxOlkoEMrau4WdVK+dcficYrwouznAS83XRSPjH7Cg2m7Qmytaa5pHiaR/iZBll6m6/Z+iMczGvYJoGlhtSZBcfEw/g3oYnqRk1lrrbezeldiNYNAprmZuHRVOr++TZSVlgFqpx/xKBbdcS+nLLd7T92Tp+2Hb/iN09abFFrtKwLowdo8IbRDddAD171mQjbLy4/xJe9h2w4mwdrzd526KTGFeP7GPKC97fHnt3ynSCgbO5lsrdLIOuMzv+HJ5uqlsqYrnzRVbbc1NaniHZE6aY7Z9xOHq3sAyNruJkeCBAQbEdN5dN0BvmzlcRIfbiPlLlzzHWL08w5ldjXDbbWe+tzh/wYCTMP3tLtx8IgcML3WWkzHJC+CA==
    MYSQL_USER: AgBj9r9q6WLPNQqJeT1BDXU7w6RuwZkpBeqUuVhckuGNZoLM1mJD6yUzT8EfjFByXGovc2DFOpn59TCdL/yfAaSl4vHjs60GqwFIFhQCluKbaYRjFbOTQwT8pWJbZncdL8pZKBMb80d7xD5xhEfQN1QT+/nCrPMibx+Q2/nq7tnhqu+tVorjIxRaVGDzhCGdzSkCMHF4biMeTiRUjfIrwpke7BSnhEgAum5TaW09qGnbw11nAC3vRUR8frLa+LX9PetdJIwcWNa4vt4WbB4f+P4uafwFSxtwQsugrp3WLzyL2GucJPimEuOEys7FAOcTgr7qsVRcZClkajpOXnQAcNwvG75Jy4TvEeI2jEptlWIq6iy4LBesewIlDJD9laBSvLV26RtCGGgpO9md68K0WNlhBGZQ9htAfo9igKXUg2dZT6lK+/Oui6flQGhsqZkfLHkiaZcTvq7jOGp9xQ45nrv5jFEZyUAoV0nbH72M4htlTMK4IaCEj8l4ASlXdensKYvsta8XDKY9o2yNkSvQzKwfkFpmX+8Xna50nOMS9SC3B2VHPCYLsqNK4voBaoDVwiHJs5h/uGxq72quw1sKHAljbKMM+AlDjclrqfEhb9pHLg++qCZoraK7zDz/h/T2eNIpnd2x56aEJN4Fs6Yjt4Ex9nph2m61YMdchnBQJjG54pxM1T37RDK22PV6Zl4lr5o1dNwafBVjOuPpgBUKJEE7kKVexvoj9JH6
  template:
    metadata:
      creationTimestamp: null
      name: community-service-credential
      namespace: linkfolio
    type: Opaque