---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: community-service-credentials
  namespace: linkfolio
spec:
  encryptedData:
    MYSQL_PASSWORD: AgC4PqcWX6kXxdukAf6dDkn7AWAbYTR1p6dsIUOwQ4gMTlj/9Rf0IGr27vD3JEDsrfH/w3kfT/TIxX9ZG4yVu1X0uboW9agzEC3N4PKwL6YW0JmIjTznpmQhz29/RKOwicmCZcFDgRyxWFR51KojhxfzNDay2R9BSQTjrZah5UnAvSI7paMjJ9kkrVKrnRd/P7bU2902/aRCYNkYLbYCE8Z4zQdF0sWme3UoQBTqIlQ8v0dbwDFa81Kkvmr7tjuP6WGCHee6saK4KajMX2k+gDKwKFxakRYsc6SE/k9Iz7JbanEqR/DA//t+O5OlzMnmVQxUceOE3luyVj2gndPpnN6UG3ijJn/Todz52zUtahknfY1Jv4mxf0Z0hrwOftI6lNEVNZiPnjtmj9woM8U4em2vD6FYybifj3/+B+sHQP14MsmV3Xro+IdqcQGceGa8b8VyqLx60+rtd8myJtc72oTz32kVaSD6u0/+lLKgO3u7kme6ombgiP7xrJ2IhPiSOKBLyju8+MeCmUTY6+5zO0xWmNj8MSQeTO+1U1NHL75rLBAigDmt0SYQOwgDGYNJmHkwUDC6Cy8TZY4i1SjQ6ZgNd285gHyMC8okW4XxSR5OKuratmGKJB5mJhjnLI8suc67mkRbafVWxNNJG9/OFdsTWa78Tm3o8ckG6gV16stnhFN/KlsYDLu3kY6QBdG2OvsKQpXf75RN/A==
    MYSQL_USER: AgBaVICfxeZn+Lhpel2SsfrDH5NPx8Hbd0UabutVBJl8M4s1Sy36tjPTsby8gfr8JJre1nB9Qp/wn+cD65IduCcO/5Mee6KPL5PK6oKHoR1o4N68npwqvkxP8JYwHJoNbcvmRAFMXDKHD0TW5be4BRSGJLCL2XTaRBl6bpsY1/w8NvKjJ70tAqPrs76A9yBssrLJA5ecOCPukgGkdzrxThe/Y+TKopTbKqqx6dyiuQIzzxfXFH16XqupYA1J7HXWi0/cZmr/t4Zapp64fBGv11pG07W2bK7xW6EEVJqmcsAHdKKTxhZQ+njOBJFJjYDROYLXjX9cyavAopeJM2+eiH5lKESjMGDVTsHR3nyrgRoIq8yeG9YHGjx5Lhbt2cVjC7kWSICrRj0HeExgfh31A0kZzB9AIALap2LU5VeVIaYK6m3LDZABxDAcpvt4iVI2MLs579E5EU0me74srRToCp8HX9pVraYRKv2HDed4/PywsrkNU1OKPP1I6GWNPpggpwowxfhGFLbLSj2FjgTLHF9/8e7Wez0pI2wZBpnYxccxOwf4R/S4oXm01+7bgZ4l7F1oZsfZ/mHuu4XyznR48Orj05Nqzh2nGzvA2+NlkeMo32X8LDn0iq1RilnFuQJoPyP3CGEQCmXtFaMy4x1TnWilfN0xJtfWHjHgWUt5mplk92rqrthOlNRzdTmcrFR8FzZblDmCvgviuy+FqXkV4bVvHgcT/+a+pjmi
  template:
    metadata:
      creationTimestamp: null
      name: community-service-credentials
      namespace: linkfolio
    type: Opaque