apiVersion: v1
kind: ConfigMap
metadata:
  name: support-service-config
  namespace: linkfolio
data:
  # DB
  DB_HOST: "shared-mysql:3306"
  MYSQL_DATABASE: "support_db"
  JPA_DDL_AUTO: "update"
  JPA_SHOW_SQL: "true"
  JPA_FORMAT_SQL: "true"
  SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "30"

  # Redis
  REDIS_HOST: "shared-redis"
  REDIS_PORT: "6379"