apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: support-pod-label
  template:
    metadata:
      labels:
        app: support-pod-label
      # --- Monitoring Annotations ---
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/support-service/actuator/prometheus"
        prometheus.io/port: "8084"
    spec:
      containers:
        - name: support-container
          image: h6bro/service-support # CI/CD에서 관리
          ports:
            - containerPort: 8084 # application.yml의 port와 일치
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: support-service-config
            - secretRef:
                name: support-service-credentials