---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: support-service-credentials
  namespace: linkfolio
spec:
  encryptedData:
    MYSQL_PASSWORD: AgCclECEcwExPUIXUuB0JaGiZrgvpXVt5HsFL4kCG1c1asDHcJ2z38I9JkXvgMKWJ168i62fGBJwn+L4EwoEocWxjdnQw12R5PoZWRtLOClBBQnDKyrr/xwitGPbSWUo0ME0YKetKm7gOasBAOMltVTui4KiIleIFTNhA2OeEnnRWC0BDEFtvizUcQon2C3KIgoC4RDkB/tJEUF6RyHfFqsYk2TpA/zyOsxMt6/mOiaG+y6qu6TzpRCUeNOXCY2dtmH3Qd40c8xYZ5yCKMuBu1U4nZdck+D+dpfJ3Vt3LxJAMLqRdps+vzWOvFxzB39Q8pjHvNJzvUgyG0abTgNT0ZfiDGT24Ju/T+S4YHfg2dKKEQDNf13ZpO9HHC4YbduYWqpwjUvgtRWQfqQZNFOasykqU8J5vu4jjKnMBvAlVUFcWkyOYD+KqHKte3ui92qzHfpAqY7ik6c97haS3SZSN4fk8p4xiHbs9D2z0IANZPP9bDMpVCMMcp5Dj0dCBymN/32ezLRXbaOdM2J3hYx/6CUSvTkn86SAMWG8Ky7hRu4S2QfeHk7eeIFYhANZc1Ha2vT5lshTumnhrpvUpBHJ1PrAEX88/fNlv9FW566LkN2PP9S0S05IenoIXvkrpRhzRkozMHpMk/DCdG+cWMc4DM0diFMIK0E2I+i1KbWvYZl6mGTU1XtsYlI1pk7KUcNOP6BtMLzLe0IpJA==
    MYSQL_USER: AgBzBvJom2r8qJglwJ+Xb3xdSkiDVfnV2XpHs7SykO+b+ShcidF1OPgBw0yGoTNxBFpq6fb6/cRh6ATnuMSL2qBRudFziOZVU/qT0lhCVNGXWPSd7WfA9Wii+bw4h2lhFlfctVmz3runYEyEgsmxPq5iL0nqVFi2Ra94CAqbk99DvgrsKX0AdTPVTtN029ko8kNZ/IL7dmSjlu2z3LnwE9lh3QBtDhhZpFyPUDJ+s+jM5287XHnQgeuR1sUx2n20J5TG83KlOU3HWYRaUv8IGdJ/7vUdnlNgfygOIrLwn8ELp4dPbjFW/4a2tY4sy08llfRWzkicGmXZrxUjh0UQdtHqqZ/i54NWp5R4zamWcshmW0/amRGZQXrRFlGgZFt4kxbBeJyHaQ+sjwnkeWfIm2oCPcg2z1sSS54WqgghvwwkvurkjOT50h4hU0GVl9r28leMDLNwuw79zsfRwhU8UlRZqBaW42jDjy6bMAXPowO9Xhcd6FCYx+sZqXcoXFl14EAbMSpJN0PuVQDyrvoWp5yunuV3Oph5Tfc0QVVGtlYw+mYXlInIEOiwKyfOX7yEq1Gq8EbRUv6E5Hs/cGMHVJ1W55khOH/C4MDmcmYNxZSABxwmYDVo37hsFC+pgiAcZUM9qcyS0VaMutFKm2UwqnXTmDljvYo57pfevlojV4eBvX9EVLX93ppP9y7SRy3F7SrlMlSStUcEkJJOScHJhK8uW6z/HjIB6g==
  template:
    metadata:
      creationTimestamp: null
      name: support-service-credentials
      namespace: linkfolio
    type: Opaque