apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-pod-label
  template:
    metadata:
      labels:
        app: auth-pod-label
      # --- Monitoring Annotations ---
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/auth-service/actuator/prometheus"
        prometheus.io/port: "8081"
    spec:
      containers:
        - name: auth-container
          image: h6bro/service-auth # CI/CD가 업데이트할 이미지 이름
          ports:
            - containerPort: 8081 # auth-service 포트
          resources:
            requests:
              memory: "512Mi" # 최소 구동 보장
              cpu: "200m"      # 스케줄링 성공을 위해 낮게 유지
            limits:
              memory: "1Gi" # Spring Boot 구동 시 튀는 메모리 허용
              cpu: "1000m"     # 초기 구동 시 CPU를 좀 더 쓸 수 있게 여유 둠
          envFrom:
            - configMapRef:
                name: auth-service-config
            - secretRef:
                name: auth-service-credentials # auth-service용 시크릿