apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkfolio-infra-database
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: 'https://github.com/HeoJunHyoung/linkfolio-manifest'
    targetRevision: feature/unified-infra-app-of-apps
    path: overlays/development/database-commons
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: linkfolio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true