apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: msa-app-development # Argo CD UI에 표시될 애플리케이션 이름
  namespace: argocd         # Argo CD가 설치된 네임스페이스
spec:
  project: default
  source:
    repoURL: 'https://github.com/HeoJunHyoung/linkfolio-manifest' # 본인의 Git 리포지토리 주소
    targetRevision: dev
    path: overlays/development # 추적할 디렉터리 경로 (개발 환경)

  destination:
    server: 'https://kubernetes.default.svc' # 대상 쿠버네티스 클러스터
    namespace: linkfolio              # 리소스를 배포할 네임스페이스
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # 대상 네임스페이스가 없으면 자동으로 생성