apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: linkfolio
data:
  DB_HOST: "mysql-user-service:3306"
  MYSQL_DATABASE: "user_db" # DB 이름
  JPA_DDL_AUTO: "create"
  JPA_SHOW_SQL: "true"
  JPA_FORMAT_SQL: "true"

  REDIS_HOST: "redis-user-service"
  REDIS_PORT: "6379"

  # GRPC_CLIENT_ORDER_SERVICE_ADDRESS: "static://order-service:9099"

  # Kafka
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "10.0.2.9:9092"
  SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS: "10.0.2.9:9092"
  SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: "10.0.2.9:9092"