apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: linkfolio
data:
  DB_HOST: "mysql-user-service:3306"
  MYSQL_DATABASE: "user_db" # DB 이름
  JPA_DDL_AUTO: "create"
  JPA_SHOW_SQL: "true"
  JPA_FORMAT_SQL: "true"
  GRPC_CLIENT_ORDER_SERVICE_ADDRESS: "static://order-service:9099"
  APP_FRONTEND_REDIRECT_URL: "http://127.0.0.1:5173/auth/callback"
  REDIS_HOST: "redis-user-service"
  REDIS_PORT: "6379"

  SPRING_MAIL_HOST: "smtp.gmail.com"
  SPRING_MAIL_PORT: "587"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
  SPRING_MAIL_FROM: "no-reply@linkfolio.com"
  SPRING_MAIL_FROM_NAME: "LinkFolio"

  APP_VERIFICATION_CODE_EXPIRATION_MINUTES: "3"

  # OAuth 리디렉션 기본 URL (ngrok 미사용 시)
  APP_OAUTH_REDIRECT_BASE_URL: "http://linkfolio.127.0.0.1.nip.io"