---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-service-credentials
  namespace: linkfolio
spec:
  encryptedData:
    MYSQL_PASSWORD: AgC3LBwQuBdsIsZQg9bOyFTWNSnd0+IXhtgiavryBl3nkk2STjM3qYZ0bwEV5R9DHgTpsvmlGOx1g1rNexZpIxSbcIDP64TPzkBtEL9JKFvAEdOAGLH5uMvikIKGihg/+zX8kT8XPgClyUcvl8t7bANbDhxlvrPJt1mYJ97fe7wnFL4a7TXARUtZwUTjuP/9x6goSwfQ+fXSUEDjBuivZG7SL1pAWw55cAs/rtoIxl10Jhlk1wfpqLQQaZiWMcsqHVVm3Gb9M4lQV9kZVVef9nOaiSmnIzWyDL8fnEOspa5MD9NvMQfbM2sLNMNK1JsSHRujB49NE/fX7bhQwKGmOKyz4zjtPzd8TzmdjKjXbSD8dM5Sw+N8LOhGkLr7fhlR2CoPXPnTn7jFkkrK+UGoHJ93+3SibcloE01+EsTZBRrE/Ai8UIyEPLb8LHm/W2322bCbauU1cA6/LgYL097zdhMYtgWRc7lbQPP63pjXxooYj9NPlmy35O7xaKrcbJn2i1fdDaDS7jiGFjxTwiyaFEmM5y5QKE91YPKT0H+8KdZR0OrZcgmiFHbfEwPkwvUb7zfJZf2KvIhUKJVvn4Bn08ZB1knOnCwiUQZJWfmx4RvnP2YR0jvzRRu0CoaZsGoS/1Sl2MUH0VP1EHFWDxwQHCEq6jNBKrONSwzyq0X/WF8rveKu7O7CC44vVjHRWW6ipySxsFxCeatX7w==
    MYSQL_USER: AgBPl7RbaHPK6TzLCBwIqIbF1y2tIZAXlGIYYIfcXJaO942TacdUNLfIL42ClIgdjIUz7wBGR7qDR+IJMsIEKo67mVCO3mH8d0+FSuT5jWMqC2iVuMOc7+q6JPm4a1UDItkHyxmZDYBnQSUtn2L1ovYHU4KlW/FbP4uRXsxmOMvyklqXlaPYsRjexnqZxnNU2ucVRpeQTPSGsOYf3DHKolKlwcY26hqYYc8gAhu7GrC4y4AzOfk0/fwRbOvO/2oEFa3T1Tfh+zAuCzOvYgUZDoLFCu10j36OxIeea05/3MysXYQ8CIRgfFReHyrIYlgMvqU742PN0Hbrcoc2MBRc2t536mPqAOLlm46qU/42IWFxQRuJ6kIZrJ57SXLj9YwghcB/fKagCGaGIFkgIljMpMUvisw4Abi+f1EgAD3MMPrSyacdxvKNkuqgtdU4womN53PqUss/Ujmg0n5uoLcQp7Rf9J+VD+ik0WIk79kXOccfmsWe7u37gPl/aNK83dHzLHu+GODkqra4ZPENvDW60vyZtfo9rkXj8yC+sh7EghKFeuaFZkBy5QXSDJ91KxfFky139b1+9RifAeQriKI0cHFDyz1SFvBel6MvOGAJqFuRqFGcDTkG+dJog9OvEbkk0qxdgiADXK7mwwoosOmsF1qOMzDETwGM87vn6SAU6IGEr/jdGFo7dg5t64Qmty6x1mC2vLMofPUHbc4b9tLaE3C5j/yMQg==
  template:
    metadata:
      creationTimestamp: null
      name: user-service-credentials
      namespace: linkfolio
    type: Opaque