apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-pod-label
  template:
    metadata:
      labels:
        app: portfolio-pod-label
      # --- Monitoring Annotations ---
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/portfolio-service/actuator/prometheus"
        prometheus.io/port: "8082"
    spec:
      containers:
        - name: portfolio-container
          image: h6bro/service-portfolio # CI/CD가 관리할 이미지
          ports:
            - containerPort: 8082 # portfolio-service 포트
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: portfolio-service-config
            - secretRef:
                name: portfolio-service-credentials