---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: portfolio-service-credentials
  namespace: linkfolio
spec:
  encryptedData:
    MYSQL_PASSWORD: AgBPT9CfkWXjaX5q4SoECV+74+5zmfIFQSZoQRn/N6kCXOck8XTbfHOSgAAdWx7EcGZPIXe2fKLhyw/IWUwfa5tI74Bc7tVKtSdID43MgRVB5aFFFAejLQjzZkXqrQJmO+B+6r4aImACEx/a28OhpxHLW5xmq/WeAyH5XD0vgZMioWuC4WCIYXV/FM2MUeN6urD6n+QcjLdHXVEQHFoSqEUdO4uLYvgjv/w4ExRyCfeSW7tDpSZqRSj4yHqB+0oanNOG5jtqVmhjVqddVrpCWKbhHmll4ie5fS1kFXNTEjG2JMrVTEH0mfHrcQZT3rMOeCfaCWU2lYrd4jd60omJeKa2Eb/qrey6LofeOnZ2grmKb2CmAmVxOAigMysvLKkvPJmk9uFvlxYPSnbxFN320vhReeG4+HUiedVzwnhv/AYEa8AcHLZr983YTbOfNOBrKZEfa+y2hJ43t4uPZ+twzGtMYXXT2de8PI7VZLXvEZ3N646h/X8R2gvVvJGFSu0UCLPHsc+w9oWbdixu5DeYSq9opzhL4C8ywsw5b2BjZZz/TfTVFbjfKBoTUY4tJQ+YSAWK9bPPg9N7DWNNcVntrNqLR7fbX9cD96uh/y5fwpoxaZaWfNCrcBWoXBblgY3749vEqXYGZ1S4Q3Vg3rO/gWY5wdkyejFp55DgLNqNHeZOgEY0YWiF3m6yWLTCVgsi1xqSqnFqQevXpw==
    MYSQL_USER: AgAxV/Ju7l76MntAVJcJUAce1A3WGLaQPis11JHyWqq4lcA9M2OJy4AfXJL+nowMuUBWaY0xBj91eg7S5riBr4tY+1S/nB8UHyA/J6GNd6yVoNMBdPC1r4ix35fxI+E+OBOZnor64Ah15exITcrjan7xcOH6SfbgIHxjxn1qdHi5r0qYTN03DUQftkA8JxkEsZ96EB6914ELCMelbvs6b9QpB7tsELwCCBI9b7IdkzbJU0dxiVmTxTylB8FOY+VE7kVuTmz8uhsHixLB5VdVj1MIR+iIfQUVvyUJaVKHwUl20Qm4/f2dA2MG30KNr+eGHSEg6BBcmZTi13axfHlyQRS/MubH0wgzr3zKYuV11RaX5s95UCwJfypg2kTDbupl/BiJ4JbjEefAIUL5lNvBywVvXyTesUfuiJgp8Xnl7+cZp1dESh/TjT2Tf9RliZN1rWiucgA1xfsSSVgLidvnTLXGCwVngJ4G39v0GcrV2rJYfgzfJ4EeWhTDxkhezG7J9vjOl/4l4fLRI4Cw0ccY0PQZ0Rt8ZUuIyr5V/Hrsnr82Vzd6vOU45EZ6naT8LcuruFxX6iLRgV9tml6OQ+FRTF4i6H5aR8ttEGbuHpRgehNzcUyiA0dqrfMdwen5kUBEKN+70Vj7IIS9pWHvTym8+lti0KB2eDFDALZfTAWV0ddIrhLPj2TFkMiYOQbOTOyYmyV1A1ouTT33RN8tJa/ctS/pYeZccxpBaxPT
  template:
    metadata:
      creationTimestamp: null
      name: portfolio-service-credentials
      namespace: linkfolio
    type: Opaque