apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-auth
spec:
  serviceName: "mysql-auth-service"
  replicas: 1
  selector:
    matchLabels:
      app: mysql-auth
  template:
    metadata:
      labels:
        app: mysql-auth
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          command: ["mysqld"]
          args: [
            "--character-set-server=utf8mb4",
            "--collation-server=utf8mb4_unicode_ci",
            "--log-bin=mysql-bin",           # 1. Binlog 활성화
            "--binlog-format=ROW",           # 2. Debezium이 요구하는 ROW 포맷
            "--binlog-row-image=FULL",       # 3. 데이터 동기화에 필수인 FULL 이미지
            "--server-id=101"                # 4. 고유 서버 ID (auth-db용)
          ]
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config # auth-service용 ConfigMap
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: auth-service-credentials # auth-service용 Secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-service-credentials # auth-service용 Secret
                  key: MYSQL_PASSWORD
          envFrom:
            - secretRef:
                name: mysql-instance-credentials
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: init-db
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-db
          configMap:
            name: mysql-auth-initdb-config # auth-service용 init-db ConfigMap
            defaultMode: 0755
  volumeClaimTemplates:
    - metadata:
        name: mysql-persistent-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: manual # auth-pv.yaml과 매칭
        resources:
          requests:
            storage: 5Gi