apiVersion: v1
kind: Service
metadata:
  name: mongodb-chat-service
  namespace: linkfolio
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None # Headless Service (StatefulSet 연결용)
  selector:
    app: mongodb-chat