apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ingress.yaml
- ../../base
images:
- name: h6bro/service-apigateway
  newName: h6bro/service-apigateway
  newTag: ef1af60
- name: h6bro/service-user
  newName: h6bro/service-user
  newTag: ef1af60
