apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config # 대상 ConfigMap 이름
  namespace: linkfolio
data:
  # ngrok 환경에서 사용할 값으로 덮어쓰기
  APP_OAUTH_REDIRECT_BASE_URL: "https://impressionless-connaturally-jonie.ngrok-free.dev"