apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-user
spec:
  serviceName: "mysql-user-service"
  replicas: 1
  selector:
    matchLabels:
      app: mysql-user
  template:
    metadata:
      labels:
        app: mysql-user
      # [0] annotations 설정
#      annotations:
#        prometheus.io/scrape: "true"
#        prometheus.io/port: "9104"
    spec:
      # [1] InitContainer 추가: Exporter용 설정 파일(.my.cnf) 생성
#      initContainers:
#        - name: exporter-config-init
#          image: busybox
#          command: ["sh", "-c"]
#          args:
#            - |
#              printf "[client]\nuser=root\npassword=%s\nhost=127.0.0.1\nport=3306\n" "$MYSQL_ROOT_PASSWORD" > /etc/mysqld-exporter/.my.cnf
#          env:
#            - name: MYSQL_ROOT_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: mysql-instance-credentials
#                  key: MYSQL_ROOT_PASSWORD
#          volumeMounts:
#            - name: exporter-config
#              mountPath: /etc/mysqld-exporter

      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: user-service-config
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: user-service-credentials
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-service-credentials
                  key: MYSQL_PASSWORD
          envFrom:
            - secretRef:
                name: mysql-instance-credentials
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: init-db
              mountPath: /docker-entrypoint-initdb.d
            - name: binlog-config
              mountPath: /etc/mysql/conf.d/debezium.cnf
              subPath: debezium.cnf

        # [2] MySQL Exporter 수정: 설정 파일 사용
#        - name: mysqld-exporter
#          image: prom/mysqld-exporter:v0.15.1
#          ports:
#            - containerPort: 9104
#          args:
#            - "--config.my-cnf=/etc/mysqld-exporter/.my.cnf"
#          volumeMounts:
#            - name: exporter-config
#              mountPath: /etc/mysqld-exporter

      volumes:
        - name: init-db
          configMap:
            name: mysql-user-initdb-config
            defaultMode: 0755
        - name: binlog-config
          configMap:
            name: mysql-user-binlog-config
        # [3] 공유 볼륨 추가
#        - name: exporter-config
#          emptyDir: {}

  volumeClaimTemplates:
    - metadata:
        name: mysql-persistent-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: manual
        resources:
          requests:
            storage: 5Gi