apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-user
spec:
  serviceName: "mysql-user-service"
  replicas: 1
  selector:
    matchLabels:
      app: mysql-user
  template:
    metadata:
      labels:
        app: mysql-user
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: user-service-config # user-service용 ConfigMap
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: user-service-credentials # user-service용 Secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-service-credentials # 👈 user-service용 Secret
                  key: MYSQL_PASSWORD
          envFrom:
            - secretRef:
                name: mysql-instance-credentials
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: init-db
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-db
          configMap:
            name: mysql-user-initdb-config # user-service용 init-db ConfigMap
            defaultMode: 0755
  volumeClaimTemplates:
    - metadata:
        name: mysql-persistent-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: manual
        resources:
          requests:
            storage: 5Gi