apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-community-deployment
  namespace: linkfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-community
  template:
    metadata:
      labels:
        app: redis-community
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379