apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/support-service

images:
  - name: h6bro/service-support
    newName: h6bro/service-support
    newTag: 8cf15bf