apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-instance-credentials
  namespace: linkfolio
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgCJUWjS7YIkoBsy8RX3ciSZGiYSLni8ppNEdaNHGMCSrP8/hhPXLMapkYmJJd5TpYoDvqhWBeRD/C7BUu6m5Q6p4eZacKYzQS5KBTnobTVMuG9huAOmePsNiZN3MtF4WciBstVI887VGOuFzCA2j4Q5d/QsjUXLPBTjgXgh9kQ0eIleHzQ5suZWzhYXFRdNCmJdbXoZmNYA+zNLUfsNqevpV9i/wls6SQkg9fj8J21qosKheiH5c7xrLmXLnAV0AwsazqvU04sHc2EGEGlHFkfoN1Bp2Tbqq100U3cy+eKgmgyd1yGODHb1G4fm+B9kKv1upXzJ/qghZVOFiJ5y5VxBEWOoTUgi2KSOV+AUjc0yZxKFF1+k24xHKQl23xYYDATNJLN1J64YiBRZ/2Pm8w+h9gXmmgFIQr4i9e44uX08LxQQMALq1f2CmcMjVixEtyGRPWvpXYVshBUxpJsheKa0Wk29iqtU4WLS7zqz7xtNQLhuiK4/zAsE6+oDWm/5a7jxlY3NDYIUpIHAE9Cft6E3s77cAo/xnnYezBsD/H8z0/NXchwBG5VSKFYiAIPc/e12oPFutCxlqFzTHxp3qtp0m0sEdT3fgcZNQL1rZ92BQixdlIHyCAQel4rU/GVcDxKqeTB8eM8DX8FVuNqavMNhcgAFkt8fJhRo1L18tZX6fIPuA3XdBUoaBOUQ1Ura7LEJOUfRpBHQfg==
  template:
    metadata:
      creationTimestamp: null
      name: mysql-instance-credentials
      namespace: linkfolio
    type: Opaque