---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-instance-credentials
  namespace: linkfolio
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgAePsfaLNscuh7HeZPSo4TS3N9kPdzoCHpLODZ7ygbD3jexdzO/Sr+7n7fyEhYY/EUA+R+kIIeplxbE/JMWJGCEynceFHcTddAdZlNNIPTI2ugDfmLrSZyLGERn0214LNBq1irnCSnfQBrHt6MnPTCV9P6AY3JXozITdw8DfmceVoZP7JUWrA2kcXCtoTPOke5DwgZlYB3RmT754fNz7IFlgy2JWFBsBA6IZ12RtZ/3qvFOrus7e33+m3aYJCR1p2hNa7zKpWGSAyQVdFtzZfu0LX3Ldle1qThoJFbb5jhF+G2X6OkAkmDYkimVHsngfR5JQNtyZQ3DYtcGLLVS5YqoxsTr9NEpNMv0fxm4zYpO2SgIz+tHUrvNzH6+x64mo9MB8DKD7tCKAywQnTbMbm2eln+ae5En89sM5LK/3pORjCn2h4i8Sw1Hsq/GswnmpgGoAsDgelzMpT2BJoaYvp4kLmvbQvBnuQVY12aNFVSXvL5l/usgTfCoW+XbJrVjEtBy1L0rdYiZg2HEdaegBIycSP6kx53gRkB6vQQnj8AaBjXZAv6B/nYO3seQIUW0Eq+CY5y3fkRdVQ9d4O6mfGu6KhDZdoMZE3/mYWwbqLGkVk9OU7WugZNzmfS4Kn33vsNqY86veVPrJrinsxg+Zg9yLn6H1McQlTH/UFMhNZtwm4AR4OOWRO77MDvjPj2EIVD3tt3rm9u/Fw==
  template:
    metadata:
      creationTimestamp: null
      name: mysql-instance-credentials
      namespace: linkfolio
    type: Opaque
