apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-deployment
  namespace: linkfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-pod-label
  template:
    metadata:
      labels:
        app: chat-pod-label
      # --- Monitoring Annotations ---
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/chat-service/actuator/prometheus"
        prometheus.io/port: "8083"
    spec:
      containers:
        - name: chat-container
          image: h6bro/service-chat # CI/CD 빌드 이미지
          ports:
            - containerPort: 8083
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME   # 앱(application.yml)이 찾는 변수명
              valueFrom:
                secretKeyRef:
                  name: chat-service-credentials
                  key: MONGO_ROOT_USERNAME       # 실제 Secret에 저장된 키 이름
            - name: MONGO_INITDB_ROOT_PASSWORD   # 앱(application.yml)이 찾는 변수명
              valueFrom:
                secretKeyRef:
                  name: chat-service-credentials
                  key: MONGO_ROOT_PASSWORD       # 실제 Secret에 저장된 키 이름

          envFrom:
            - configMapRef:
                name: chat-service-config
            - secretRef:
                name: chat-service-credentials