apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - redis           # Redis Pub/Sub
  - redis-insight   # Redis GUI
  - db              # MongoDB
  - deployment.yaml # Chat App
  - service.yaml
  - configmap.yaml
  - sealed-secret.yaml