---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: chat-service-credentials
  namespace: linkfolio
spec:
  encryptedData:
    MONGO_ROOT_PASSWORD: AgC0dusypQbFB0rVNOUWFWUm4U+oeiVyCdJiUQIfhEhu6DpTPRL4A88z65CUR5+3mIYNYL4ZT8MSShr6xiotWO0KDkGeVFkNXFrhx+uKPgGBimAJmosgEn3aCAjq871+H4x50LMa+0PDhyfseAvBxPXkbxYcaO9MQRn1Z8fd6OUW5tVYOZfbaQkzcOXxW6oC/QxlF/xTOIM4hpPC5vewJPMgWzDrmwxv6ShOJFwj+kJTM30D79LrYU1KCvsGqVOhfyd+itvUaKwRu3+7qyIJhQCBCwEaEaODmPrJap7VQR1UdIudKDXdgcm6DAz3zou0MWVx3Zn5kzFeBbrI7KU0Qm0gVnmMnHGoutOrJ5BqZR+q+8FtkB91n5f1NUMADjCVnswhLiDP++uJoXObiEu31FwQZ+3pfbO6baCwz9/clxfpGULP3Up8C2/ZODPxHFqWB9YC1peXCOrh+cIbcckQJmY4oe9Pez7NAgxYElyqbK5dhX7ywIVu1CeAzmxDC8B99wKtLiSYLCdBVjojqLUDU4eEjdJaw1+Ot/fzt6A2Yn2TTJUIVbrv7eYN06+vYkRZ9N9nvo9xtJTEPutK5WjAusCsqkyTNXDGg5v63tfQtDQ0Zb2bPXCsgpxHo2FP2yyAYENfYKjpISMFzrks2aPo5KI/IJtc0mWYBGx8MQVP5TOTGFrnQJEW5wUNg0E0kd51C3t/yFalL0WtYg==
    MONGO_ROOT_USERNAME: AgA5YKVDqWg3/2Q7DKnVSoNVVhY6IgFwMT77J2InAxeiwRtKplR5YrqoNF55qZ8l5D4t1afXwzJ/vbRwpVJE5KS8Sn55OAO83boTM8VloVGrrR0a6NntGRwLGetRY8N/qaGL6/mbj18GgztmuVpflswd5q+xqRfsAosiQ+iM+bm3tiYhPBiKO8QlNl3l8cB9l6gH2iK2C5sa2sH9bSlQyp2VldzIY5QVmGiPB/X66pwEnhJX5xpn0tCooPZbX12RIOi9jlPj2EiIHbVLAjKyAeH2vuxfWp2OKUe1Df6XxzczJmHJSZjvnZPi3iCiCPrsegKg2l9WzHBJ5ykpXQ9TosN76O4ut9sJLrPh4Wh8d80wA9Qv5xme/baN88oDzuGdOUB+bPrc0RHV39LI9+irHGqx/KuEeg30nvv5yQchP/Djk0KeV3VFKJpp9p1KDxXgCEoYJolxcfUR09jUtLFYmqC8PElUSYH+98VSYdZIkocAQV9CKEdJrwhi3i8jg22jZciQl+s5VIfmieymebfydMOdN79h+PX+JFt0WMJOZWQm4lqYu/liFq+Y6YYaaQIVyOI94rU2pIOuZWHMOZKmkB+8Y6eODhe3ojsg0WT9nm0hwFMegfwOvG00xxCvYSLsusGgcymUO80WP1sO+RM/kipWyadk+PK3N3ORGWPcGPQ2lADqp0KurPjreHk/f12XYJuYAFmV
  template:
    metadata:
      creationTimestamp: null
      name: chat-service-credentials
      namespace: linkfolio
    type: Opaque