# [수정] 아래는 일반 secret임. 변환해줘야 함!!!!
apiVersion: v1
kind: Secret
metadata:
  name: chat-service-credentials
  namespace: linkfolio
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: "root"
  MONGO_ROOT_PASSWORD: "password"