apiVersion: v1
kind: ConfigMap
metadata:
  name: apigateway-config
  namespace: linkfolio
data:
  # 1. User Service Route
  SPRING_CLOUD_GATEWAY_ROUTES_0_ID: "user-service-route"
  SPRING_CLOUD_GATEWAY_ROUTES_0_URI: "http://user-service:80"
  SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0: "Path=/user-service/**"

  # 2. Auth Service Route
  SPRING_CLOUD_GATEWAY_ROUTES_1_ID: "auth-service-route"
  SPRING_CLOUD_GATEWAY_ROUTES_1_URI: "http://auth-service:80" # auth-service.yaml의 Service 이름
  SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0: "Path=/auth-service/**"

  # 3. Excluded URLs (백엔드 application.yml과 동일하게)
  APP_GATEWAY_EXCLUDEDURLS: "/user-service/welcome,/actuator,/v3/api-docs/**,/swagger-ui/**,/user-service/swagger-ui/**,/user-service/v3/api-docs/**,/auth-service/swagger-ui/**,/auth-service/v3/api-docs/**,/auth-service/auth/signup,/auth-service/auth/login,/auth-service/auth/refresh,/auth-service/auth/logout,/auth-service/auth/check-username,/auth-service/auth/check-password,/auth-service/auth/find-username,/auth-service/auth/password-reset/send-code,/auth-service/auth/password-reset/verify-code,/auth-service/auth/password-reset/change,/auth-service/auth/email-verification/send,/auth-service/auth/email-verification/check,/auth-service/oauth2/authorization/**,/auth-service/login/oauth2/code/**"