apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway-pod-label
  template:
    metadata:
      labels:
        app: apigateway-pod-label
    spec:
      containers:
        - name: apigateway-container
          image: h6bro/service-apigateway
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: apigateway-config
            - secretRef:
                name: apigateway-service-credentials