---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: apigateway-service-credentials
  namespace: linkfolio
spec:
  encryptedData:
    JWT_SECRET: AgDCg8htrj87InfQermghWVW2JyHpDcTyg7n6mcRq6Ips5vDHDtA/9BQzuzNby+F0WRl8Vs7GH0NQt/qMe0gyKT8GMw1joTMh6DV/SKsMzCdFb/XNDDc17pdlOoC6qpIkeRh2IHBzjxZo/FvheeoJAHZZMdgVx6g5ruZd8DZANCRHmlmqd8XrhkASOlyOPRd3sRVjSqyMTAOICG55uDd1ZaJ6jGgA3TRLbOI+C3kDipLVksk3B8rehfnhdBqCxOP3nBwikaT/8GLuwg5+pWOYPbNrdlYIiDR5PZEdZb66TssFTZRTt8lplfT5x+ByVAeZf/x8P8EkEEgE6wdLiFWCSgpOOKgX7eFjt3S+c2r/dtbyXfFpPUrOIWNaz57z7ex0sd42aEJMWwzS/qkBKzSAX1+D/hJGusAlcgT572eBjmFzmcvcIEogqQIKaJsZz47BWlxHO96jcBnYiYchbUe0ig7D//fEHoLhNqodkw3jEe4xuc4muapuNAlP5gsrCDtmYvQnO++/YzfXo5/k+pKMDnInWD/gSdSL2gkPLLGPbbWbBmPU3Je3owMpbrb5WrTk3Uj7iF4koH5nHUZnuvSMXkER9AYf4+W+lZrKDYLQ9w6baGD+34wbUrHuaXjflXroRmgfNxavRns5Jow/Asqz72pvuJvP87QOnrPl2dURFS4/KXfoKryZEOU0/Yu/rROGeyJ8ItZzwlANWppOS8CWdAHtm6lg1xCSBXON/aB/kHJwMPfspI7xpWzPpr6f2qMd6oqGeOQ/Z4UylINyPD4xqPKVB76wAw02AWiKXWatxbzrwvej/M2Xt0CU1ZqMI+EpNTg
  template:
    metadata:
      creationTimestamp: null
      name: apigateway-service-credentials
      namespace: linkfolio
    type: Opaque

