apiVersion: v1
kind: PersistentVolume
metadata:
  name: chat-mongodb-pv
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /tmp/k8s-pv/chat-mongodb # MongoDB 데이터 저장 경로
    server: 10.0.2.8 # NFS 서버 IP