apiVersion: v1
kind: PersistentVolume
metadata:
  name: portfolio-db-pv
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /tmp/k8s-pv/portfolio-db # portfolio-db 전용 경로
    server: 10.0.2.8 # NFS 서버 IP