apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-mysql-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.2.8
    path: /tmp/k8s-pv/shared-mysql