apiVersion: v1
kind: PersistentVolume
metadata:
  name: support-db-pv
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /tmp/k8s-pv/support-db # NFS 서버 내 경로
    server: 10.0.2.8 # NFS 서버 IP