apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/portfolio-service

images:
  - name: h6bro/service-portfolio
    newName: h6bro/service-portfolio
    newTag: 8cf15bf