apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-support
spec:
  serviceName: "mysql-support-service"
  replicas: 1
  selector:
    matchLabels:
      app: mysql-support
  template:
    metadata:
      labels:
        app: mysql-support
      annotations: # [Monitoring] Prometheus Exporter 설정
        prometheus.io/scrape: "true"
        prometheus.io/port: "9104"
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: support-service-config
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: support-service-credentials
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: support-service-credentials
                  key: MYSQL_PASSWORD
          envFrom:
            - secretRef:
                name: mysql-instance-credentials
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: init-db
              mountPath: /docker-entrypoint-initdb.d

        # [Monitoring] MySQL Exporter Container (수정됨)
        - name: mysqld-exporter
          image: prom/mysqld-exporter:v0.15.1
          ports:
            - containerPort: 9104
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-instance-credentials
                  key: MYSQL_ROOT_PASSWORD
            - name: DATA_SOURCE_NAME
              value: "root:$(MYSQL_ROOT_PASSWORD)@(localhost:3306)/"

      volumes:
        - name: init-db
          configMap:
            name: mysql-support-initdb-config
            defaultMode: 0755
  volumeClaimTemplates:
    - metadata:
        name: mysql-persistent-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: manual
        resources:
          requests:
            storage: 5Gi