apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/community-service

images:
  - name: h6bro/service-community
    newName: h6bro/service-community
    newTag: 8cf15bf